export const ordersData = [
  {
    id: 1,
    poNumber: "#PO-2024-001",
    vendorName: "Acme Supplies",
    orderDate: "2024-02-14",
    orderTime: "17:40",
    deliveryTime: "7h 20m",
    fromWarehouse: "Gurgaon",
    toStore: "Mumbai",
    transportMode: "Truck 20 ft",
    packagingType: "Close body",
    quantity: 1,
    totalWeight: 4000,
    itemsCount: 4,
    assignedTo: "Mohit",
    employeeId: "52t520lt61264",
    status: "live"
  },
  {
    id: 2,
    poNumber: "#PO-2024-002",
    vendorName: "Global Traders",
    orderDate: "2024-02-14",
    orderTime: "18:30",
    deliveryTime: "8h 10m",
    fromWarehouse: "Delhi",
    toStore: "Bangalore",
    transportMode: "Truck 32 ft",
    packagingType: "Open body",
    quantity: 2,
    totalWeight: 6000,
    itemsCount: 7,
    assignedTo: "Amit",
    employeeId: "52t520lt61265",
    status: "live"
  },
  {
    id: 3,
    poNumber: "#PO-2024-003",
    vendorName: "Prime Distributors",
    orderDate: "2024-02-13",
    orderTime: "16:20",
    deliveryTime: "2h 40m",
    fromWarehouse: "Pune",
    toStore: "Hyderabad",
    transportMode: "Truck 20 ft",
    packagingType: "Close body",
    quantity: 1,
    totalWeight: 3500,
    itemsCount: 5,
    assignedTo: "Rahul",
    employeeId: "52t520lt61266",
    status: "responded"
  },
  {
    id: 4,
    poNumber: "#PO-2024-004",
    vendorName: "City Wholesale",
    orderDate: "2024-02-13",
    orderTime: "15:15",
    deliveryTime: "1h 30m",
    fromWarehouse: "Chennai",
    toStore: "Kolkata",
    transportMode: "Truck 24 ft",
    packagingType: "Container",
    quantity: 1,
    totalWeight: 5000,
    itemsCount: 2,
    assignedTo: "Suresh",
    employeeId: "52t520lt61267",
    status: "unresponded"
  },
  {
    id: 5,
    poNumber: "#PO-2024-005",
    vendorName: "Neha Enterprises",
    orderDate: "2024-02-15",
    orderTime: "09:00",
    deliveryTime: "5h 00m",
    fromWarehouse: "Ahmedabad",
    toStore: "Surat",
    transportMode: "Truck 17 ft",
    packagingType: "Close body",
    quantity: 2,
    totalWeight: 2500,
    itemsCount: 3,
    assignedTo: "Vikram",
    employeeId: "52t520lt61268",
    status: "live"
  },
  {
    id: 6,
    poNumber: "#PO-2024-006",
    vendorName: "Ravi Shankar Co.",
    orderDate: "2024-02-15",
    orderTime: "11:30",
    deliveryTime: "3h 45m",
    fromWarehouse: "Jaipur",
    toStore: "Delhi",
    transportMode: "Truck 32 ft",
    packagingType: "Open body",
    quantity: 3,
    totalWeight: 9000,
    itemsCount: 6,
    assignedTo: "Deepak",
    employeeId: "52t520lt61269",
    status: "live"
  },
  {
    id: 7,
    poNumber: "#PO-2024-007",
    vendorName: "Sunita Patel Ltd.",
    orderDate: "2024-02-12",
    orderTime: "14:00",
    deliveryTime: "0h 30m",
    fromWarehouse: "Nagpur",
    toStore: "Pune",
    transportMode: "Truck 20 ft",
    packagingType: "Container",
    quantity: 1,
    totalWeight: 4500,
    itemsCount: 1,
    assignedTo: "Anil",
    employeeId: "52t520lt61270",
    status: "unresponded"
  },
  {
    id: 8,
    poNumber: "#PO-2024-008",
    vendorName: "Karan Mehta Corp.",
    orderDate: "2024-02-15",
    orderTime: "13:15",
    deliveryTime: "6h 15m",
    fromWarehouse: "Lucknow",
    toStore: "Agra",
    transportMode: "Truck 24 ft",
    packagingType: "Close body",
    quantity: 2,
    totalWeight: 7000,
    itemsCount: 9,
    assignedTo: "Sanjay",
    employeeId: "52t520lt61271",
    status: "responded"
  },
  {
    id: 9,
    poNumber: "#PO-2024-009",
    vendorName: "Anjali Singh Traders",
    orderDate: "2024-02-16",
    orderTime: "08:45",
    deliveryTime: "9h 00m",
    fromWarehouse: "Bhopal",
    toStore: "Indore",
    transportMode: "Truck 17 ft",
    packagingType: "Open body",
    quantity: 1,
    totalWeight: 3000,
    itemsCount: 4,
    assignedTo: "Manoj",
    employeeId: "52t520lt61272",
    status: "live"
  },
  {
    id: 10,
    poNumber: "#PO-2024-010",
    vendorName: "Vikash Yadav Supplies",
    orderDate: "2024-02-16",
    orderTime: "10:00",
    deliveryTime: "4h 30m",
    fromWarehouse: "Patna",
    toStore: "Ranchi",
    transportMode: "Truck 32 ft",
    packagingType: "Container",
    quantity: 4,
    totalWeight: 12000,
    itemsCount: 11,
    assignedTo: "Rohit",
    employeeId: "52t520lt61273",
    status: "live"
  },
  {
    id: 11,
    poNumber: "#PO-2024-011",
    vendorName: "Meera Nair Distributors",
    orderDate: "2024-02-11",
    orderTime: "12:30",
    deliveryTime: "0h 15m",
    fromWarehouse: "Kochi",
    toStore: "Trivandrum",
    transportMode: "Truck 20 ft",
    packagingType: "Close body",
    quantity: 1,
    totalWeight: 2800,
    itemsCount: 0,
    assignedTo: "Sreejith",
    employeeId: "52t520lt61274",
    status: "unresponded"
  },
  {
    id: 12,
    poNumber: "#PO-2024-012",
    vendorName: "Arjun Reddy Corp.",
    orderDate: "2024-02-16",
    orderTime: "15:00",
    deliveryTime: "10h 00m",
    fromWarehouse: "Hyderabad",
    toStore: "Chennai",
    transportMode: "Truck 24 ft",
    packagingType: "Open body",
    quantity: 2,
    totalWeight: 5500,
    itemsCount: 8,
    assignedTo: "Prasad",
    employeeId: "52t520lt61275",
    status: "responded"
  }
];
